apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
spec:
  containers:
    - name: nginx
      image: {{ .Values.image_name }}
      {{ if .Values.open_port }}
      ports:
        - containerPort: 80
      {{ end }}

