apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
spec:
  containers:
    - name: nginx
      image: {{ .Values.image_name }}
      ports:
      {{- range .Values.ports }}
      - containerPort: {{ . }}
      {{- end }}



