apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
  labels:
{{- with .Values.labels }}
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  containers:
    - name: nginx
      image: {{ .Values.image_name }}
      ports:
      {{- range .Values.ports }}
      - containerPort: {{ . }}
      {{- end }}

      env:
      {{- range $k, $v := .Values.env }}
      - name: {{ $k }}
        value: {{ $v }}
      {{- end }}

